fix init jira error

diff --git a/odoctl b/odoctl
--- a/odoctl
+++ b/odoctl
@@ -20,7 +20,7 @@ ODO_INIT_RANCHER='yes'
 ODO_INIT_JMS='yes'
 
 COOKIES=".odo_cookies"
-CURL="curl -s -v -l -c ${COOKIES} -b ${COOKIES}"
+CURL="curl -s -v --location -c ${COOKIES} -b ${COOKIES}"
 
 ## Common Function
 function log_error() {
@@ -47,13 +47,14 @@ function chmod_dir() {
 function help_doc_cmd() {
     cat <<EOF
 $0 <COMMAND>:
-    start     - Up container(s) to start service(s)
-    stop      - Stop container(s) to stop service(s)
-    down      - Down all services
-    restart   - Restart container(s) to restart service(s)
-    list      - List container(s)
-    license   - Generate JIRA/Confluence/Plugin license
-    cleanup   - Cleanup all containers and dirs
+    start           - Up container(s) to start service(s) and init them
+    start_no_init   - Up container(s) to start service(s)
+    stop            - Stop container(s) to stop service(s)
+    down            - Down all services
+    restart         - Restart container(s) to restart service(s)
+    list            - List container(s)
+    license         - Generate JIRA/Confluence/Plugin license
+    cleanup         - Cleanup all containers and dirs
 EOF
     exit 1
 }
@@ -113,7 +114,7 @@ function check_env() {
         [[ "$(getenforce)" == "Enforcing" ]] && setenforce 0
         sed -i 's/^SELINUX=.*/SELINUX=disabled/' /etc/selinux/config
     }
-    for _tool in "docker" "docker-compose"; do
+    for _tool in "docker" "docker-compose" "curl"; do
         output=$(${_tool} --version 2>&1) || {
             echo -e "\033[33;6m${_tool} is required in this machine \033[0m"
             echo "${output}"
@@ -123,7 +124,7 @@ function check_env() {
 }
 
 function check_odo_cli() {
-    echo "start stop down restart list license cleanup no_init_start" | grep -qw "${COMPOSE_CMD}" || help_doc_cmd
+    echo "start start_no_init stop down restart list license cleanup" | grep -qw "${COMPOSE_CMD}" || help_doc_cmd
     if [[ "${COMPOSE_CMD}" == "license" ]]; then
         echo "jira jira_plugin conf conf_plugin jenkins" | grep -qw "${COMPOSE_SVC}" || help_doc_license
         [[ "${COMPOSE_SVC}" == "jira" ]] && return 0
@@ -203,18 +204,18 @@ function init_odo_ldap() {
     echo "Access LDAP"
     while true; do
         sleep 2
-        output=$(curl -s -v -L -X GET "$phpldapadmin_url/htdocs/index.php" -o ${_curl_output} 2>&1)
-        echo "$output" | grep HTTP | grep 200 && {
-            header_cookie=$(echo "$output" | grep 'Set-Cookie: ' | awk -F 'Set-Cookie: ' '{print $NF}' | awk -F ';' '{print $1}')
-            echo "$header_cookie"
-            break
-        }
+        output=$($CURL -X GET "$phpldapadmin_url/htdocs/index.php" -o ${_curl_output} 2>&1)
+        echo "$output" | grep HTTP | grep 200 && break
+#        echo "$output" | grep HTTP | grep 200 && {
+#            header_cookie=$(echo "$output" | grep 'Set-Cookie: ' | awk -F 'Set-Cookie: ' '{print $NF}' | awk -F ';' '{print $1}')
+#            echo "$header_cookie"
+#            break
+#        }
     done
     echo "Login LDAP"
-    output=$(curl -s -v -L -X POST "$phpldapadmin_url/htdocs/cmd.php" \
+    output=$($CURL -X POST "$phpldapadmin_url/htdocs/cmd.php" \
         -H 'Accept: */*' \
         -H 'Content-Type: application/x-www-form-urlencoded' \
-        -H "Cookie: $header_cookie" \
         --data-urlencode 'cmd=login' \
         --data-urlencode 'server_id=1' \
         --data-urlencode 'nodecode[login_pass]=1' \
@@ -224,10 +225,9 @@ function init_odo_ldap() {
         -o ${_curl_output} 2>&1)
     echo "$output" | grep HTTP | grep 200 || log_fail "$output"
     echo "Import LDAP"
-    output=$(curl -s -v -L -X POST "$phpldapadmin_url/htdocs/cmd.php" \
+    output=$($CURL -X POST "$phpldapadmin_url/htdocs/cmd.php" \
         -H 'Accept: */*' \
         -H 'Content-Type: multipart/form-data' \
-        -H "Cookie: $header_cookie" \
         --form 'server_id=1' \
         --form 'cmd=import' \
         --form "ldif=$(cat odo-ldap/odo_users.ldif)" \
@@ -249,15 +249,17 @@ function init_odo_sonar() {
     echo "Waiting for SonarQube[${sonar_url}] running ..."
     while true; do
         sleep 2
-        curl -v -s -X GET ${sonar_status_url} 2>&1 | grep HTTP | grep 200 && break
+        $CURL -X GET ${sonar_status_url} 2>&1 | grep HTTP | grep 200 && break
     done
     echo "Login SonarQube[${sonar_login_url}] ..."
     while true; do
         sleep 2
-        output=$(curl -v -s -X POST ${sonar_login_url} \
+        output=$($CURL -X POST ${sonar_login_url} \
             -H 'Accept: application/json' \
             -H 'Content-Type: application/x-www-form-urlencoded' \
-            -d 'login=admin&password=admin' -c .sonarcookies 2>&1)
+            --data-urlencode "login=admin" \
+            --data-urlencode "password=admin" \
+            2>&1)
         echo "${output}" | grep HTTP | grep 200 && {
             sonar_token=$(echo "${output}" | grep ' Set-Cookie:' | grep 'XSRF-TOKEN=' | awk -F 'XSRF-TOKEN=' '{print $2}' | awk -F ';' '{print $1}')
             [[ -z "${sonar_token}" ]] && exit 1
@@ -266,24 +268,22 @@ function init_odo_sonar() {
         }
     done
     echo "Install LDAP plugin: ${sonar_plugin_url}"
-    output=$(curl -v -s -X POST ${sonar_plugin_url} \
-        -H 'Accept: application/json' -H 'Content-Type: application/x-www-form-urlencoded' \
-        -H "X-XSRF-TOKEN: ${sonar_token}" -d 'key=ldap' -b .sonarcookies 2>&1)
-    echo "${output}" | grep HTTP | grep 204 || {
-        rm -rf .sonarcookies
-        log_fail "$output"
-    }
+    output=$($CURL -X POST ${sonar_plugin_url} \
+        -H 'Accept: application/json' \
+        -H 'Content-Type: application/x-www-form-urlencoded' \
+        -H "X-XSRF-TOKEN: ${sonar_token}" \
+        -d 'key=ldap' \
+        2>&1)
+    echo "${output}" | grep HTTP | grep 204 || log_fail "${output}"
     echo "Update sonar.properties to enable LDAP"
     sed -i 's/#sonar.security.realm=LDAP/sonar.security.realm=LDAP/' odo-sonar/sonar.properties
     echo "Restart sonar: ${sonar_restart_url}"
-    output=$(curl -v -s -X POST ${sonar_restart_url} \
-        -H 'Accept: application/json' -H 'Content-Type: application/x-www-form-urlencoded' \
-        -H "X-XSRF-TOKEN: ${sonar_token}" -b .sonarcookies 2>&1)
-    echo "${output}" | grep HTTP | grep 200 || {
-        rm -rf .sonarcookies
-        log_fail "$output"
-    }
-    rm -rf .sonarcookies
+    output=$($CURL -X POST ${sonar_restart_url} \
+        -H 'Accept: application/json' \
+        -H 'Content-Type: application/x-www-form-urlencoded' \
+        -H "X-XSRF-TOKEN: ${sonar_token}" \
+        2>&1)
+    echo "${output}" | grep HTTP | grep 200 || log_fail "$output"
     docker restart odo-sonar
     return 0
 }
@@ -308,11 +308,11 @@ function init_odo_jira() {
         sleep 2
         output=$($CURL -X GET ${jira_url}/secure/SetupMode!default.jspa 2>&1)
         echo "${output}" | grep HTTP | grep -E '200|302' && {
-            echo "${output}" | grep 'Set-Cookie: ' | awk -F 'Set-Cookie: ' '{print $NF}' && break
+            atl_token=$(echo "${output}" | grep 'Set-Cookie: ' | awk -F 'Set-Cookie: ' '{print $NF}' | awk -F 'atlassian.xsrf.token=' '{print $2}' | awk -F ';' '{print $1}')
+            [[ -z "${atl_token}" ]] || break
         }
     done
     echo "Setup Mode: ${jira_mode_url}"
-    atl_token=$(echo "${output}" | grep 'Set-Cookie: ' | awk -F 'Set-Cookie: ' '{print $NF}' | awk -F 'atlassian.xsrf.token=' '{print $2}' | awk -F ';' '{print $1}')
     output=$($CURL -X POST ${jira_mode_url} \
         -H 'Accept: */*' \
         -H 'Content-Type: application/x-www-form-urlencoded' \
@@ -423,7 +423,7 @@ function init_odo_conf() {
     conf_dbchoice_url="${conf_url}/setup/setupdbchoice.action"
     conf_dbtest_url="${conf_url}/setup/setupstandarddb-testconnection.action"
     conf_dbtype_url="${conf_url}/setup/setupdbtype.action"
-    echo "Waiting for Confluence Server running ..."
+    echo "Waiting for Confluence Server[${conf_url}] running ..."
     while true
     do
         sleep 2
@@ -565,7 +565,7 @@ if [[ "${COMPOSE_CMD}" == "start" ]]; then
     sleep 2
     ${DOCKER_COMPOSE} ps
 # Emm......
-elif [[ "${COMPOSE_CMD}" == "no_init_start" ]]; then
+elif [[ "${COMPOSE_CMD}" == "start_no_init" ]]; then
     if [[ "${COMPOSE_SVC}" == "" ]]; then
         set_host_for_sonar
     else
